### PR TITLE
Add openSUSE installation instructions

### PR DESCRIPTION
**Pull request by rombert**

### CODE REVIEW

**Comment by kravemir** [comment]
First, thanks for contribution.

Second, PR seems to be fine. I thought, openSUSE uses `dnf` also, but I wasn't sure. On which openSUSE version did you test it?

**Comment by rombert** [comment]
@kravemir - openSUSE uses rpm, just like Fedore/RHEL/CentOS, but the higher layer is zypper, and not dnf/yum - those were never supported options on openSUSE/SLE.

The packages are available at https://software.opensuse.org/package/ddccontrol , they are there for the rolling Tumbleweed variant and for the 'stable' supported releases - Leap 42.3 and Leap 15.

**Comment by kravemir** [comment]
I have merged the PR. Sorry for very late reaction, I have forgotten about this PR :-(

**Comment by rombert** [comment]
Don't worry about the timing, thanks for merging :-)

**Pull request merged**
